<?php

declare(strict_types=1);

/**
 * @file
 * Provides a product review entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function product_review_theme(): array {
  return [
    'product_review' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for product review templates.
 *
 * Default template: product-review.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the product review information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_product_review(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function product_review_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_reassign':
      // Anonymize product reviews.
      $storage = \Drupal::entityTypeManager()->getStorage('product_review');
      $product_review_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($product_review_ids) as $product_review) {
        $product_review->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function product_review_user_predelete(UserInterface $account): void {
  // Delete product reviews that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('product_review');
  $product_review_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($product_review_ids)
  );
}
